services:
  postgres:
    image: postgis/postgis:latest
    container_name: msservergpstcp-postgres
    environment:
      POSTGRES_DB: msservergpstcp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres_network
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  redis:
    image: redis:latest
    container_name: msservergpstcpredis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save "" --appendonly no --databases 3
    restart: always
    networks:
      - postgres_network
    healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  postgres_network:
    driver: bridge 
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16